### ISSUE TITLE
error in file opening

### ISSUE THREAD

**Issue by chekanov** [diana-hep/root4j#4]
Hello,

 This is very interesting project. I was trying to compile and run, but unfortunately I could not open a root file with histograms with RootFileReader.java. Does it support histograms? Here are the errors:

>      [java] Exception in thread "main" java.lang.NullPointerException
>      [java] 	at java.util.Properties$LineReader.readLine(Properties.java:434)
>      [java] 	at java.util.Properties.load0(Properties.java:353)
>      [java] 	at java.util.Properties.load(Properties.java:341)
>      [java] 	at org.dianahep.root4j.core.DefaultClassFactory.<init>(DefaultClassFactory.java:39)
>      [java] 	at org.dianahep.root4j.RootFileReader.init(RootFileReader.java:217)
>      [java] 	at org.dianahep.root4j.RootFileReader.<init>(RootFileReader.java:183)

**Comment by vkhristenko** [comment]
Hi Sergei

Thanks for reporting. The project itself aimed at using TTrees mainly and this fork did not treat histograms at all, although that can be done. 

i updated the readme to reflect that the primary use of this project was to use together with [spark-root](https://github.com/diana-hep/spark-root) and Apache Spark.
